version: "3"
services:
    frontend:
        container_name: frontend
        build: ./frontend
        ports:
            - 3000:3000
        depends_on:
            - backend
    backend:
        container_name: api
        build: ./backend
        command: npm run cron
        restart: always
        ports: 
            - 27000:27000
        links:
            - mongo
        depends_on: 
            - mongo
    mongo:
        container_name: mongo
        image: mongo
        ports:
            - "27018:27017"